# Verwende ein offizielles Python-Image als Basis
FROM python:3.8-slim

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die requirements.txt und installiere die Abhängigkeiten
COPY src/${APP_NAME}/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Kopiere den Code von der jeweiligen App
COPY src/${APP_NAME} /app/src/${APP_NAME}

# Setze den Startbefehl für die jeweilige App
CMD ["python", "/app/src/${APP_NAME}/app.py"]
