name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [app1, app2]  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.app }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./${{ matrix.app }}

      - name: Run Unit Tests
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.app }}
          pytest --maxfail=1 --disable-warnings
        working-directory: ./${{ matrix.app }}

      - name: Run SAST with Bandit
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.app }}
          pip install bandit
          bandit -r src/ || true
        working-directory: ./${{ matrix.app }}
